### ISSUE TITLE
Wiki sidebar placement

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#109]
I love the sidebar for the wiki - is it possible to use some sort of conditional markdown magic to make it only appear on the wiki page? I find it off-putting on the other pages. 

https://github.com/drupaldiversity/administration/wiki/Drupal-Diversity-&-Inclusion-Participation-&-Moderation-Guidelines

**Comment by cleverington** [comment]
@AlannaBurke Unfortunately, it is either 'on' or 'off.

As an alternative, I could go ahead and add those pages not yet listed.

**Comment by sugaroverflow** [comment]
Yeah, it looks like it's either on or off, sorry @AlannaBurke. I agree that it's off putting, but maybe if we segment everything under a good title (like the Moderation Guidelines and Participation Guidelines headers) it'll be organized? :)

Closing this issue for now since there's not much we can do given Github restrictions.
