### ISSUE TITLE
CWG recommendation

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#11]
Based on conversations in the Dec 8 meeting, we would like to offer a recommendation to the CWG for how to handle diversity/inclusion issues (and successes) in the public/social media space.

**update:** based on hours and hours of conversation on March 23, we would *still* like to offer recommendations, especially in light of the private nature of CWG matters.  How can the CWG handle things in a way that makes community members feel safe, respected and heard?

**Comment by logickal** [comment]
Saying what I've been stewing on: I think the biggest worry in the community is that between the way that Crell managed to frame things by having the first word and the (understandable) obfuscation/wishy-washyness from Dries + the decision to keep evidence private  has made many people wonder if there is some secret pact that lets some community members ride others out on a rail for 'reasons'.  IMO that's going to be a hard notion to disabuse.

**Comment by mlncn** [comment]
[these are just my own thoughts]

The main public reason stated for the attempt to expel Crell from the Drupal community is that his views about women are beyond the pale, which Crell has framed as a matter of sexual relationship between consenting adults. This sets up diversity & inclusion efforts for a major backlash for a decision most diversity & inclusion advocates had no part in.  The Community Working Group, the Drupal Association, and Dries need to take steps to mitigate the fallout from this decision, and then to support diversity & inclusion in a strong, consistent manner.

Some suggestions:

* Publicly reject the revealing of someone else's private, personal information as an acceptable starting point for a CWG action.
* Enforce specific reprisals for specific accusations.  For instance, removal from leadership positions for publicly espousing values inimical to the project.  Disavow anti-women beliefs and step down from leadership positions appears more immediately reasonable than "leave the project".
* Provide public criticism for public behavior, which will be much healthier for the community, and may even help us all to become better.
* Assess issues on a case-by-case basis.  Out of leadership for this.  Expulsion from community forums for that.  There's not even a community definition of being made to leave the project (is there?); the highest defined level is being banned from places the Drupal Association controls.

I fear the worst of both worlds is coming where the inane cult of wealthy white male victimhood (which managed to get their patron saint to the Presidency of the US) has a martyr and forms a vocal faction around this, exposing how many anti-women people there are in the community (good luck expelling them all, especially when they can hide behind defending someone's right to have private beliefs), while the power structure responsible for deciding to boot Crell feel they've done their work, and action to be inclusive and diverse actually stalls even more.  This is the danger of symbolic action against anti-women views (with draconian consequences for one individual) instead of doing the hard work of truly being welcome to disproportionately excluded groups. 

If Crell really holds such anti-women views *and* these views are really at odds with community beliefs, why haven't they come into conflict?

Specifically, if no one else in the Drupal community is against taking steps to improve our gender imbalance and treating transgender people with respect, why did https://www.drupal.org/node/752452 end in a stalemate?  If it's true that with Crell as PHP track lead, there's been no women speakers in 27 sessions (and sorry i'm not able to look this up, but we as a community *do* need to be keeping track of that), that's something which we needed to address by the 15 or 20 mark; if Crell opposed addressing this that's the opportunity to articulate community values, and who can be in leadership, based on public, Drupal-based words and actions. (And not saying it's easy in the PHP world to include women speakers but we know it's possible https://philsturgeon.uk/feminism/2015/08/17/women-speaker-ratio-conversation-loop/ — and if it is honestly, truly, not possible, there should be a PHP track session about addressing that.)

Our community seems to be saying we're fine with there being profound inequality, but we're shocked and appalled to find someone would subscribe to an ideology that would endorse this.  (In the United States the broader culture basically has this approach to race.  It hasn't worked out well.)  Condemning a reprehensible belief system is very hollow, and likely counterproductive, when our actions do not do much to indicate our disagreement.  Inequality + no effort to identify and address the causes = many people concluding the disadvantaged are inferior.  If we really oppose the ideology of inferiority, we'll oppose it the most effective way possible: by addressing the causes of the reality that matches it.

**Comment by jannekalliola** [comment]
I would had liked to read the following things from an official statement: a) process - how we ended up here and who made decisions, was the person in question handled professionally and according the defined processes, b) were there material complaints / issues / etc. to justify the decision that was made.

No details, but description of the flow of things and then clearly stated that there were reasons to expel the person in question and those reasons cannot be discussed due to privacy of the people putting them forth.

**Comment by AlannaBurke** [comment]
@jannekalliola As far as part of a) goes, this is what we were told in [Slack](https://drupal.slack.com/archives/C1BCR7XL6/p1490316804879704) by Adam Hill:

>Hey folks - just some clarification. The CWG made the decision that this issue needed to be escalated to Dries as per our charter. Dries made the decision to ask Larry to leave the community. The DA then decided to remove Larry from his positions at DrupalCon. The DA board ratified that decision based on appeal by Larry. Removing reasons for decisions, this was the process.

**Comment by MichelleCox** [comment]
For me, a big problem I had was that the initial response sounded like he was being asked to leave due to his _beliefs_ and then later it was clarified that there were _actions_ but that those actions can't be shared due to privacy reasons. So we are left with just vague assurances that he did do something to deserve this even though he says he didn't and the community is left wondering who to believe.

While I fully understand wanting to protect the safety and privacy of people reporting problems, I do think we need some more transparency. It's not enough to just say, "Trust us, he did something so bad that we're kicking him out but we can't tell you what it is." Even if it's anonymized, there should be _something_ concrete said about what he's actually being accused of. Otherwise all anyone can do is speculate and that tends to do more harm than good.

**Comment by davidhwang** [comment]
With respect and acknowledgment for as much discretion and privacy as possible for all involved, extraordinary circumstances warrant extraordinary responses from those who choose to exercise extraordinary measures. 

The most recent events have shown that there are weaknesses to the CWG process, namely what happens if one party chooses to go public and the other does not? How can we avoid appeals to the court of public opinion, particularly if the CWG is primarily a reactive body, and a distinctly non-public one at that?

**Comment by jordanpagewhite** [comment]
In general, is there a place where the CWG (or DA or whatever entity this falls on) discusses the extent to which behavior/beliefs in someone’s personal life can effect their participation in the community (given that those behaviors/beliefs are not brought into the work place in this hypothetical example). I have seen a lot of speculation as to whether or not this decision was made based upon personal behavior/beliefs vs. whether or not those behaviors/beliefs manifested in any way in a work setting. I think that some more clarity on that issue would at least quell some of the speculation.

**Comment by RainbowArray** [comment]
I get the sense that what would help people feel more settled is a statement from those who made these decisions that “This isn’t just about a person’s personal beliefs, but also about actions within the community that have been reported, but which we can’t share publicly due to privacy concerns.” 

However… that’s pretty much what the DA did say in their statement and many don’t seem satisfied with that. People want more details even though sharing more details may not be possible.

I think it's also fair to say something along the lines of "while the Drupal community values a wide variety of individual beliefs, having someone in a position of leadership whose beliefs involve one gender's dominance over another as part of a natural order is pretty problematic when that leadership position involves the ability to favor one gender over another"... but that's pretty much what Dries said in his statement, and many people didn't find that satisfying either.

Since there is a good amount of confusion, maybe it would be helpful to have another statement that makes clear the timeline of decisions, who decided what and on what basis (beliefs/actions and the interactions between those two), as well as how that connects to the code of conduct. I think it's fair to say that the code of a conduct is a guideline, but not an authoritative and definitive set of rules that will necessarily cover all potential situations.

I think it's also fair to be clear the limits on what can be shared publicly: if some description of the nature of concerns can be shared without revealing who reported concerns (as that would trigger another set of likely very concerning problems), then that would probably be helpful. If it's not possible to share anything at all, just being very clear about why is probably good.

But again, I feel like the statements already given touch on all these points. I don't really want to be critical towards the delivery of those statements. These are delicate matters and putting together statements on a short timeline isn't easy.

**Comment by AlannaBurke** [comment]
I think we might suggest that in the future, with any issues that require communication to the Drupal community on matters like this, **all communication should be issued from the DA or CWG, and not from Dries**. A blog post, no matter whom it is from, is a poor way to issue important and sensitive information. 

It is clear that in this case, it has done more harm than good in the public eye. It seems the blog post was a reaction to Larry's post, which is understandable - but I think a lot of misunderstanding could have been cleared up by taking more time to issue an official DA/CWG statement first. Dries could then be free to blog about it, but no matter his position, I don't think his blog is should be the official mouthpiece of Drupal. We already have one in place.

**Comment by davereid** [comment]
I'm pretty firmly in the belief there are actually two different decisions that have been made here. The DA removing Larry as track chair and session from DrupalCon, and Dries asking Larry to step down his leadership and involvement in the open source project and PHP-FIG. The DA cannot decide on the latter at all, which would help explain why we all cannot reconcile the blog post from the DA vs Dries' blog post. They are at the source the same issue, but two different responsibilities and decisions.

**Comment by AlannaBurke** [comment]
Define a channel by which a member of the Drupal community can report incidents of “X person in the Drupal community has said some really hateful things online (outside of the Drupal Community) and I don’t think it represents the community. These things were not directed at me and this is not an interpersonal dispute." How is “Outside of the Drupal Community” defined? For example, our Slack channels are not official. 

To discourage abuse of this reporting tool, we suggest something like “The CWG is not interested in reports of lawful, consensual personal activity of users outside the community that do not violate [better] community guidelines [than we currently have]"

We would also suggest increasing the size of the CWG to increase its capacity.

**Comment by alexpott** [comment]
A recommendation that I've made privately to the CWG is that they publicise their work more. Or maybe the Drupal Association should. Drupalcons are always a very busy time for the CWG and some other communities publish post-conference reports on the workings of their CWG equivalents. Yes the minutes are online (https://drive.google.com/drive/u/0/folders/0BzkTwEOVwF93cUVXVm9RQXp2QnM) - which is great but perhaps we could publicise them more and link them from future conference's Drupal Code Of Conduct page (eg. https://events.drupal.org/baltimore2017/code-conduct) so that people know that these are not just words but represent things that we, as a community, act on.

**Comment by AlannaBurke** [comment]
One thing I would suggest to change in the CoC is this line:
>If you do not feel that you can speak up, contact the Community Working Group immediately with evidence of the incident. 

I would change `evidence` to `information` - I worry that this is off-putting if the issue was a verbal one. I do not want to discourage reporting of incidents.

**Comment by AlannaBurke** [comment]
From the Conflict Resolution Policy:
>If this fails, get a third-party (e.g. a mutual friend, and/or someone with background on the issue, but not involved in conflict) to intercede.

Could we get a group of community members willing to work with people as the third-party, like peer mediators? This worked surprisingly well in high school, if I recall. Has anyone tried it in a group like this? Could this be a first step that the CWG helps mediate?

**Comment by cmcintosh** [comment]
I feel like, https://www.drupal.org/dcoc needs further expansion on the definitions.  What happens when those things are violated, and the corrective measures for each bullet point.  The language seems to nebulous atm.

**Comment by zendoodles** [comment]
Since ultimately the decisions and actions taken were done by the DA, I think recommendations should be addressed to the larger audience of the CWG, the DA, and Dries. 
One question I would ask would be, what the expectations/suggestions were when the CWG escalated to Dries, and if the escalation was wholly based on evidence presented from outside of the Drupal community

**Comment by catch56** [comment]
There are always going to be some cases that require anonymous reporting.

However I'd like to see an additional process whereby issues about an individual's behaviour can be discussed either semi-publicly or in a way which can at least be summarized and reported back. This obviously requires them to be such that the original complainant(s) is not concerned about anonymity.

This would be useful especially for issues where there are patterns of behaviour relating to multiple different people or expressing particular views in opposition to the inclusive goals of the project as opposed to interpersonal disputes.

The current discussion going on in the DD&I channel over the past four days has been close to how I could see that being conducted.

**Comment by catch56** [comment]
A model to look at in general might be 'transformative justice' http://www.usprisonculture.com/blog/transformative-justice/ - this has developed out of trying to deal with violent incidents in communities where calling the police may not be safe for anyone involved (i.e. the person running that blog is an activist in Chicago).

**Comment by EclipseGc** [comment]
I'd like to see us agree on an MVP for removing members from the community. It seems like a good first step toward solving some of the issues specific to recent events while simultaneously setting a bar for community disclosures.

Others have suggested more transparency in general both in recent issues and in day to day operations of the CWG. While this would be nice (and a good long term goal), I think it distracts from and complicates the matter of removing individuals from our community. To that end, I propose the following MVP(s) for basic member expulsion

**Scenario 1: Clean and Simple**

1. Public, Community wide confirmation of a CoC violation

1. That there is a victim(s) (not who they are, just simply that they exist)

1. Vague references to the sort of CoC violation in the broadest of terms

**Scenario 2: Pattern of Behavior**

1. Ample evidence for non-CoC violating offenses of a nature deemed obstructionist to the project or the progress of the community.

1. Historical timeline of CWG issued warnings and responses to those warnings.

Obviously, there's some additional work to sort on defining obstructing the project/community. This needs to be more than simple technical disagreements except in the cases that true impasse is reached and no 3rd party is capable of mediating. 3rd parties should ALWAYS be introduced into these situations. I know I've personally had huge technical disagreements that sat at impasse for months and a 3rd party was able to fix the issue. It's like 2 gears spinning the same way, they're both working and working hard, and toward the same goal, they just can't work together. Neither needs to go, but a 3rd gear spinning the opposite direction between them brings it all into harmony (ish).

I'd note that no disclosure of any sort is needed so long as issues can be **resolved** in private. However, expulsion is a **failure to find a solution** and as such becomes the domain of the entire community. We must all understand at least the very basics of what are at stake and why certain actions are being taken. Protecting victims must always be a priority, but a lack of transparency about the existence of victims at all is completely unhelpful and will feel exclusionist and unnecessary.

Finally, while it might be a separate issue, I'll point out that given sufficient circumstantial evidence, anyone could bring any claim to bear against any community member, and if the CWG "protects" the victim to the exclusion of the accused even being able to answer accusations, that seems to be asking for abuse and generally runs against the grain of fairness. We all understand that retribution might be feared, but you can't be convicted for a secret crime by a secret court and feel like you were treated justly. It's just not in human nature and it will ultimately disenfranchise our community. There is a balance somewhere, and we are definitely NOT there.

**Comment by helenasue** [comment]
What about community members who have been reported as problematic having to be part of a ‘group sensitivity training’ program in the Drupal community where they have some in-depth talks and group therapy for a period of time to work their way out of a 'community suspension'? No one is beyond redemption, and people are capable of change, even if it's hard and slow and painful sometimes. I don't know if anyone is so far gone that they deserve to be exiled forever. 

From this suggestion, it came up in the chat by @eclipsegc that this could also be beneficial in general for community leaders - although @heyrocker brought up the good point that 'community leader' right now also lacks definition.

**Comment by RainbowArray** [comment]
I think there are two big parts to why there is so much community discussion about this particular situation

The first part is interest in “Why did this happen to Larry, somebody I know either personally or as somebody prominent in the community?”

The second part is “Do I need to worry that this could happen to me?”

I think that second part is where there could really be additional messaging, and it’s important to have that in order for people in the community to feel safe. I think a few things people want to know are:

1) “Am I at risk of being asked to leave the community because of my kink?”

2) “Are my beliefs something that are going to be questioned? What are the beliefs that can get you removed from the community?”

3) “Is it just believing a harmful idea that can get you removed? Articulating that idea somewhere on the Internet? Articulating it within the Drupal community? Making somebody uncomfortable at a Drupal event?”

4) “If I am in a situation where I might be ejected from the community, what is the process?”

As much I trust what has happened in this particular situation, I can certainly understand people asking questions like these about how safe their standing is in the community. People build their careers and lives around Drupal, and it is understandable for people to feel their safety is threatened when it is possible to lose all that for reasons that are not clear for privacy reasons. Finding a way to reassure people seems like an important goal for community health.

While I think most people understand that releasing the details of this particular situation is problematic due to privacy issues, they could accept that if they had more solid answers about whether or not they might find themselves in a situation like this in the future. One issue that has been raised about this particular situation is that people want to know if they should have any safety concerns about a person who has been asked to leave the community if they choose to continue to attend community events. While privacy concerns make that conversation understandably difficulty, I do think that's a fair question for people to ask and want answers to.

**Comment by beeradb** [comment]
I’m interested in which capacity Dries made his decision. He wears a lot of hats in the community, as Acquia CTO, BDFL/Project lead, President of the Board, and Trademark owner. When making a decision about a competitors employee that seems like a conflict of interest to me. I’m not saying he didn’t make the correct choice, but he wears enough hats that it can be difficult to know which one he’s acting under at any given time.

**Comment by drnikko** [comment]
Please see also the list of questions made by @YesCT here: https://docs.google.com/document/d/12EXNOXhNj5PoH5T0ATuIeRV8L3sIbqiSnIU9hkzQTw8/edit 

You can contribute anonymously to this doc ^

**Comment by les-lim** [comment]
I'd like to know to what degree actions taken by the CWG, the DA, and Dries are expected to carried beyond the immediate purview of DrupalCon and the Drupal masthead.  The DA acts as the fiscal agent for several local Drupal communities and camps.  If someone is asked to leave the community, and that person later submits a session to Twin Cities Drupal Camp, will TCDrupal risk losing fiscal sponsorship for selecting her session?

**Comment by heyrocker** [comment]
I am not on the DA BUT traditionally the answer to that has been yes. For instance when the individual was banned from DrupalCon last year, they were also banned from any DA-funded events.

**Comment by catch56** [comment]
One thing that's caused a lot of confusion and still confuses me personally too in regards to process:

Both Larry and Dries say that Dries "asked him to leave".

The DA/Board have revoked track chairage and a session at DrupalCon Baltimore. As yet there's no DrupalCon ban nor Drupal.org ban. Having your track chairage and a session cancelled are not a 'ban' - lots of people don't chair DrupalCon tracks or give presentations at them.

That could be where they decided to leave things in terms of concrete actions - not ejected but not given a prominent public platform by the Drupal Association any more, after being asked to leave voluntarily in the first place. Or it could have been first concrete steps in an ongoing process, with the blog post interjecting in the middle. This is mainly a process question as far as I can see, and could have been much better communicated. The subsequent clarifications have helped, but I'm still not clear, and I've paid close attention to this.

On the opposite hand, the person who was banned from DrupalCon last year, since that remains completely anonymous, is presumably still able to visit local camps which don't have a link to the DA. If local camps wanted also to exclude people who are banned from DrupalCon, are they even practically able to do that?

**Comment by Badfaerie** [comment]
So, there are a lot of comments about what this means for Dries, the DA, the CWG, and for Larry, but not a lot about what it means for diversity and inclusion. I pose the following questions:

Was the person removed part of a protected class?

Was the action(s) taken supportive of a more inclusive environment for under served populations?

If this action was not taken, would there be a harm to individuals of under served populations?

I would also mention that the standards for a person in a leadership role has to be higher than for those not in leadership. In this situation, the "community leaders" are project spokespersons as well as "mentors". This is a virtual position of power. This power dynamic has been evident in the posts of certain long time contributors, "core contributors" in particular.

It is recommended that these individuals be asked to lead on diversity and inclusion issues as they come up. As mentioned above, they would need to be trained in how to identification and amelioration of gender, racial, and sexual identity bias. This is and always will be a "best effort" endeavor. Reaching out to partner with groups such as Fembot/FemTechNet to assist in training and advise would be a great resource.

**Comment by chx** [comment]
> On the opposite hand, the person who was banned from DrupalCon last year, since that remains completely anonymous, is presumably still able to visit local camps which don't have a link to the DA.

Are you bloody kidding me? First of all local camps subscribe to the travesty you people call the DCoC, second as far as I am concerned I was not banned from DrupalCon but from Drupal. And I know the CWG is just as good as using weasel words as everyone involved here because they will deny to the end of the world of banning me but after telling me (instead of Xano) is banned from DrupalCon they added this:

> We hope that you will consider this carefully, as further action could have a significant impact on your ability to participate in the Drupal project and community. 

Well, how do you read that if not a total ban.

**Comment by chx** [comment]
So @heyrocker's answer is a surprise. Or not. We know that the Lullabots are fed inside information by the CWG and they behave as their attack dogs on twitter, drupal.org and reddit. This happened to me and Crell both. I can give you the links for eg. [reddit](https://www.reddit.com/r/drupal/comments/60y9mq/larry_garfield_on_harassment_in_the_drupal_project/?sort=old) how odd is that all the well known names of the oldest comments here are *all* Lullabots. But anyways: do tell me, what do you know about me being banned from local camps that *I* do not? For I am not. The reason I do not go to any of those is because I wanted nothing to do with Drupal any more and after these events, I want even less if such is possible.

**Comment by heyrocker** [comment]
@chx What makes you think I was talking about you? I wasn't, I was talking about this incident:

https://www.drupal.org/node/2729687

Also your claim that my company acts as an "attack dog" for any other organization is unfounded and radically out of line.

**Comment by AlannaBurke** [comment]
This thread is intended to be a constructive way to make recommendations - I know that everyone has a lot of feelings about this issue, but this is not the place to argue, and I urge you all to please consider your responses and keep your language and criticism constructive.

**Comment by chx** [comment]
Whatever, I deleted, I shouldn't.

**Comment by rubyji** [comment]
I don't see anything useful or productive about chx's participation in the Drupal Diversity & Inclusion Working Group's issues, and given that he says he wants nothing to do with Drupal, I propose he not be permitted to participate in conversations here or in our Slack channel.

**Comment by heyrocker** [comment]
Since @chx has decided to delete his comments, I include them here so it can be clear what we are responding to.

First comment:
`On the opposite hand, the person who was banned from DrupalCon last year, since that remains completely anonymous, is presumably still able to visit local camps which don't have a link to the DA.

Are you bloody kidding me? First of all local camps subscribe to the travesty you people call the DCoC, second as far as I am concerned I was not banned from DrupalCon but from Drupal. And I know the CWG is just as good as using weasel words as everyone involved here because they will deny to the end of the world of banning me but after telling me (instead of Xano) is banned from DrupalCon they added this:

We hope that you will consider this carefully, as further action could have a significant impact on your ability to participate in the Drupal project and community.

Well, how do you read that if not a total ban.
`
That comment was then deleted and replaced by this one:
`So @heyrocker's answer is a surprise. Or not. We know that the Lullabots are fed inside information by the CWG and they behave as their attack dogs on twitter, drupal.org and reddit. This happened to me and Crell both. I can give you the links for eg. reddit how odd is that all the well known names of the oldest comments here are all Lullabots. But anyways: do tell me, what do you know about me being banned from local camps that I do not? For I am not. The reason I do not go to any of those is because I wanted nothing to do with Drupal any more and after these events, I want even less if such is possible.`

Which was also deleted.

**Comment by rubyji** [comment]
chx is trolling and I recommend everyone not feed him. (edited)

**Comment by sinasalek** [comment]
I just searched news headline for Drupal and it didn't look good :(. I recommend everyone to [read this](http://www.inc.com/sonya-mann/drupal-larry-garfield-gor.html) one, it seems Dries already modified his blog post after receiving so many negative comments.

As some fellow Drupalers mentioned it is now way out side the community and had already made an impact on members, lack of any response for the decision makers is not acceptable, but since this is a complicated issue, understandably they may need more time to prepare proper response.

But if they decided to just ignore the whole thing or came up with even worse response, even-though non of us are decision makers or in charge of the Drupal community, there are still few things we can do to recover at least part of the damage inflicted to drupal community's reputation.

Here is my suggestion:

1. Working together Summarizing the comments and prepare an open letter addressing Dries and DA (including the most practical suggestions) and sign it (via an online petition for example), demanding them to respect the community and take proper action.

2. If that didn't succeed, we can then make a public announcement on behalf of Drupal community and distancing the community from this incident and the way it handled by the decision makers. Making it clear that Drupal community as a whole stands by its code of conduct and inclusivty even if those currently running it, do not.

Note that we can work with CWG toward this as well

Also i understand that some people (specially women) may not feel comfortable around someone with Larry's belief even when those belief do not influence his/her actions (I'm just using Larry as a sample since i don't know for sure what really happend) in community (this maybe one of the reasons Dries and DA made such a drastic decision) we people can easily be influenced by words and interpret each other's actions in a completely different way before and after knowing more about each other. IMHO that is what inclusivity is all about. Knowing that we are all very deeply different, but also knowing that when dealing with each other we follow the same rules. So i think we also need to consider this and mention it in our statement what we are really standing by and not causing any further misunderstanding by some other community members that maybe be worried about what i mentioned.

Just to make sure we can ask other community members to make comment on the open letter or the statement before going public

Condemning those participated in violating Larry's privacy and (and if possible even responding properly to their action) and comming up with a guide line and an an effective way of reporting violation of code of conduct in order to

Also if DA does not want to be really inclusive they can at least make it clear at the begining for anyone what wants to join them. something like this : YOU HAVE TO HAVE THE RIGHT PRIVATE LIFE TO JOIN US, AND THE RIGHT PRIVATE LIFE MEANS ...

I created a doc to start preparing the open letter. Please join in
https://docs.google.com/document/d/1wzQq963HjOLoDd3jzsBAVzu1vqIDEjwjzYIcXG-Cmhc/edit?usp=sharing

**Comment by iant-ee** [comment]
I'm concerned that we have set up processes and a dedicated committee for dealing with community behaviour, yet ultimately there's still a single person who can step in and say "I don't like you, go away" without even naming the rules that the community member has broken. It's even more concerning when that person is the head of a major Drupal business and can make this decision about his competitor's big name employees.

We have the CWG. They should be ultimately responsible for behaviour. If they feel that someone has behaved unacceptably but hasn't broken any existing rules, then clearly the rules need to be amended. While any necessary amendments are being discussed it can also be discussed about whether the new rules should be applied retrospectively.

**Comment by techsoldaten** [comment]
I mm a long time contributor and fiscal sponsor to the Drupal community. A member of the board recommended I share my thoughts here and ask for people's feedback.

The Community Working Group serves no useful purpose and should be eliminated. No one in this community has a place judging other members of other community.

I say this on these grounds: 

- Secrecy: there is no useful role for a group that relies on secrecy this in a community that values transparency.

- Chilling Effects: I know many contributors who are leaving the community or ceasing to participate based on bans to other members. 

- Conflicts of Interest: There are apparent conflicts of interest amongst the people making decisions. It's likely this represents a threat to the project.

I realize the CWG has other, more banal duties, like deciding whether or not to send people emails on their birthday. So has every other secret court in the history of Western civilization, and every one of them has eventually been abused in disastrous fashion.

Also, I think it's kind of crazy that people who weigh in on sending emails are also given some kind of ultimate authority over who does and does not get to participate. We would be better off without this as part of the governance structure.

**Comment by davereid** [comment]
@techsoldaten Your statements on the CWG seem incorrect, reactionary, and insultingly dismissive. I would expect a more informed response from that board member on the CWG's actual role: code of conduct violations and assisting with mediation between community members.

**Comment by techsoldaten** [comment]
@davereid I am sorry you find my thoughts offensive. I find the notion of secret courts - or anything that functions the same way under a different name - deeply offensive.

It would be nice if the group actually did just mediate disputes between members. I am sure, 99% of the time, that's how it works. But everyone once in a while someone is asked to leave the community over their sexual activities, or because they argue their points too strongly, or whatever other reason someone comes up with to tell them to leave.

I am always amazed how groups of innovative, intelligent and well-meaning people, given enough time and opportunity, will find new ways to reconstitute the Spanish Inquisition, while others applaud / insist this is not what they are doing.

**Comment by rubyji** [comment]
As we have discussed at length in the DD&I Slack channel, the decision was made not about sexual activity or preferences. The lack of information from the DA, and poor communication from Dries has fostered this misunderstanding which is leading to massive hostility both within and toward the Drupal community. 

I do think we need a Community Working Group, but I would rather see it chartered by the Drupal Association rather than the individual project owner, who has too many conflicts of interest. It's time for our community to grow past the start-up phase which is necessarily driven by one leader with a strong vision, and into a fully-fledged organization with our own community infrastructure.

**Comment by davereid** [comment]
@techsoldaten Please read https://docs.google.com/document/d/1tcwuuip9qAMtGNir7_aD1zhWubEkisNnkG3n7CHFPbM/edit. The CWG made no such decision or judgement. This is unproductive to this discussion at hand.

**Comment by drnikko** [comment]
Hi all - thank you for the comments on this issue.  We'll be closing this issue for further comment and integrating all of the feedback into a document that we will then post for _further_ comment. :)  We will figure out a document collaboration strategy during our Thursday 3/30 meeting at 17UTC/12EST/9PST

**Comment by drnikko** [comment]
Sorry, hit "close" too quickly - consider this the "last call" for comments until we post the document.  I'll close this issue at 6pm PST March 29.

**Comment by sinasalek** [comment]
I just read [Larry's second response](https://www.garfieldtech.com/blog/tmi-part-2), frankly i no longer want to hear or read about that Gorean stuff or Larry's private or anyone's private life anymore i have had enough! To me, this is way past Larry now, we need some considering reform in both DA and CWG to prevent things like this from happening again.

I was about to prepare a draft for an open letter but i'll wait till you guys finish your summarization. But please also consider the comments on the following links, there are very good comments there :
- https://www.drupal.org/association/blog/a-statement-from-the-executive-director
- http://buytaert.net/living-our-values

**Comment by sinasalek** [comment]
As @helenasue already mentioned, people make mistake. When community bans someone for violating the code of conduct, it should be clear what he/she is being banned, i don't think that it should be permanent. There must be a way for them to make up for their mistake, regain trust and come back.

**Comment by rszrama** [comment]
Summarizing my thoughts from [this Reddit comment](https://www.reddit.com/r/drupal/comments/629214/drupal_association_dries_and_larry_whats_next/dfl6nwn/), Larry's defense prominently features the Community Working Group clearing him of any DCoC violation. It's fair to say that his framing played a role in a lot of the community feedback similarly centering around that decision. While this line of thought isn't without merit, we don't need to uncritically accept its implications or accept that either the process or guidelines have failed; they may simply be incomplete or unclear.

For example, the CWG's own charter seems to limit their scope to interpersonal conflicts involving _Drupal Community Members_, and neither the Charter nor the DCoC indicate that community members may only be banned as a result of unresolvable conflict. Additionally, the charter indicates they will advise community members on escalation but doesn't really define the escalation process or implications.

I'm not sure how many folks bothered to read through the CWG's charter after being exposed to their decision, but I'd advise the CWG to revise the charter to 1. make the limits of their scope more explicit (e.g. to clarify that the limitation of their scope does not mean there are no other legitimate grounds for a person to be banned from participation) and 2. clarify the escalation process / potential implications (e.g. that escalation doesn't necessarily mean only "issues that require the involvement of law enforcement" or that in the event an issue does not involve interpersonal conflict or require mediation as described in the charter it may be referred to Dries [or whomever] until the charter itself is revised to address such situations).

It's a real tricky situation, because neither the DCoC nor the Charter can ever address every potential case in advance that may affect diversity / inclusion. However, maintaining a "friendly and welcoming community for the Drupal project" may require actions that exceed the scope of the CWG ... and in the event that they do, the expectation should be that the relevant processes / guidelines will be reviewed and revised as needed.

**Comment by drnikko** [comment]
Closing! We will figure out a document collaboration strategy during our Thursday 3/30 meeting at 17UTC/12EST/9PST
