### ISSUE TITLE
Agenda for August 3rd Meeting

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#119]
- no team updates this week
- demographics followup?
- book club updates?
- PR for our values statement?
- discussing the slack history export
- govcon followup?
- discussing job interviews
- anonymous survey!

**Comment by sugaroverflow** [comment]
#117 prev meeting issue.

**Comment by AlannaBurke** [comment]
I'd love to talk about a potential new action item we could work on as a group. We were discussing bad job postings in the channel, and I was wondering if we could work on a set of resources for companies to help with workplace and hiring diversity. I imagine there is a lot out there that we could compile to start. someone shared http://joblint.org/, which is neat. I'd also be interested in maybe taking a survey of something like "what things in job descriptions have kept you (a marginalized person in tech) from applying to a job?" 

This is such a huge issue, and instead of just reacting to bad postings, i would love for us to be a pro-active resource to say "hey company A, here are a ton of resources on how to make your company more diverse and inclusive." 

I also think opening up a brainstorming issue in github might be helpful!

**Comment by sugaroverflow** [comment]
@gdemet do we have a followup for demographics this week?
@sparklingrobots any book club updates? :)

**Comment by sparklingrobots** [comment]
Next week (August 9) at 9am PDT we'll be starting our discussion on Twitter & Tear Gas by Zeynep Tufekci.  If you want to join in, please read chapter 1.  

We're also going to start tagging people directly in reminders so if anyone wants to be put on the reminders list, please let @sparklingrobots know. 

Thanks, @sugaroverflow!
