### ISSUE TITLE
Twitter Mentors for our community idea

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#131]
Alison shared this with us in the diversity-inclusion channel: https://twitter.com/sehurlburt/status/889004724669661184 and  we thought it would be a great idea if we could do this within our community. 

This issue is to discuss what that might look like and how we'd do it :)

**Comment by sugaroverflow** [comment]
- we should consider the relationship of this work to the existing drupal mentoring work https://groups.drupal.org/mentoring
- also possibly related to #121 resources for drupal job postings

and cool script that Alison found: https://github.com/ishansharma/twitter-mentors/blob/master/README.md

**Comment by alisonjo315** [comment]
I'd love to work on this, also bc I never use Python outside of the once in a while when I get to teach it :)

Re: Drupal mentoring, excellent point, maybe after we chat a little on GH but before too long, I could ping the mentoring channel on slack, if they're associated with the "IRL" mentoring community?

**Comment by sugaroverflow** [comment]
Sounds good!

- We might have to edit the script a little for ourselves, but it sounds like a cool project. 
- Yes! Or there might be a person we can contact that has a list of mentors or something :)

We should probably define what our idea/implementation is and then see if they have any feedback/would like to change things.

**Comment by alisonjo315** [comment]
Via Geoff Appleby on Slack:
> PHP Mentoring allows people interested in mentoring others to post a bio
> https://php-mentoring.org/

**Comment by drnikko** [comment]
@alisonjo2786 would you like to take the lead on this?  We're trying to foucs on initiatives with people willing to lead them.

**Comment by alisonjo315** [comment]
Hi! Is this still applicable, or is it morphing into the ddi contrib channel thing, or is that different?

**Comment by drnikko** [comment]
@alisonjo2786 I think if you want to lead it, we can do it.  We really can only support ideas that have a lead since there is a lot going on.

**Comment by alisonjo315** [comment]
Hey! Thank you, I totally missed the notification from GH of your reply, and I forgot to check on it, sorry for the delayed response.

Since I didn't think about this in the last week, unfortunately I'm going to have to defer to next week to think about it, I'm going out of town Wednesday morning and one of me bffs is getting married Sunday.

I was also thinking I'd love for us to push the train-top-contributors-to-be-more-mindful-and-supportive-and-stuff concept, but idk the top-contributors community well enough to have a feel for whether that would be super impractical/unrealistic... And maybe the Twitter acct mentor thing is like, closer to a "low hanging fruit" idea that could become real sooner than later.

(But do you think the other idea is unrealistic?)

**Comment by drnikko** [comment]
I'm also super late on the response here.  I wonder how we can integrate this with our move to d.o.  Since that's where "top contributors" hang out, we might be able to take advantage of that. 

I'm comfortable with any form that you want this to take, and also comfortable with you pausing on it for a while until we (the collective we) can come up with a better plan.  <3

**Comment by sugaroverflow** [comment]
Since we are moving to drupal.org, I migrated this issue: https://www.drupal.org/project/diversity/issues/2923869 

Closing :)
