### ISSUE TITLE
Agenda for Oct 26

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#144]
preliminary agenda items that will probably rollover:

- DD&I Book Club hiatus
- DD&I Contrib team updates
- Support for upcoming camps/presentations?
    - https://nedcamp.org/
    - https://www.drupalcampatlanta.com/ 
- Drupalcon Nashville DD&I + how to make it safer
- from ok_lyndsey - "Can/should we have a process of messaging people we see being targeted directly to check they are ok?"

**Comment by rubyji** [comment]
Do we need to talk about the Morten/CWG/naming names business? (Especially since I stirred up the sh*t on Twitter. Ooops.)

**Comment by sugaroverflow** [comment]
@rubyji yup, we're going to retract that we posted his name and encourage people to send reports to CWG if they have issues to report. I think that's what @drnikki had planned for that, correct me if I'm wrong.

**Comment by drnikko** [comment]
I wouldn't say retract, but we do need to write a post clarifying why we
did it, and, in general, asking for reports. @heyrocker was going to start
it, but I'll try to get something short started today


On Oct 25, 2017 6:59 AM, "Fatima Sarah Khalid" <notifications@github.com>
wrote:

@rubyji <https://github.com/rubyji> yup, we're going to retract that we
posted his name and encourage people to send reports to CWG. I think that's
what @drnikki <https://github.com/drnikki> had planned for that, correct me
if I'm wrong.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/drupaldiversity/administration/issues/144#issuecomment-339339020>,
or mute the thread

**Comment by sugaroverflow** [comment]
sounds good

if we have a post today, I can add this to the agenda, otherwise it can wait :)

**Comment by sparklingrobots** [comment]
Here's the Contrib Team update: 

Next back-end team meeting is Tuesday at 10 am PT. We are forming 2-3 person groups to work on writing tests for Drupal 8. We are still open for mentees, mentors & tester/reviewers. 

The next front-end team meeting is next Thursday at 11 am PT.  The front-end team is working on a very exciting theme project.  

If you'd like to be involved, hop on over to #ddi-contrib-team and introduce yourself!

**Comment by sugaroverflow** [comment]
Thank you @sparklingrobots !
