### ISSUE TITLE
Agenda for Nov 2nd

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#146]
items that will probably rollover: 
- DD&I Contrib team updates
- Drupalcon Nashville DD&I booth/presence + how to make it safer
- personal check ins
- DD&I response post about the morten/cwg/naming issue (if it's ready)

**Comment by rubyji** [comment]
Why is this assigned to me? Please tell me I am not facilitating. That is not in my calendar.

**Comment by sugaroverflow** [comment]
+ moving to Drupal.org (I'll update this description in a bit) #145

**Comment by rubyji** [comment]
- Update on governance process. (Fatima or Nikki?)

- Donation report (Nikki)

**Comment by sparklingrobots** [comment]
If we have time, perhaps we can discuss developing a protocol for when folks voice discomfort with what is happening in the channel.  Right now it relies a lot on whoever happens to be active at the time and we don't (or I should say **I** don't) have a good sense of what to do. 

My thoughts are that when someone voices discomfort, a *designated*, *trained* person reaches out to them with the link to our form, as well as an offer for a private conversation.  Then that person asks the channel to move along from the topic (not sure what happens if the person wants to discuss in-channel).   Just being heard and making a connection could go a long way toward helping the person figure out whether they want to be part of our work.  

It's scary (at least for me) to voice dissent/discomfort and I think we could do a bit more to help those who are willing to do so.

**Comment by sugaroverflow** [comment]
@sparklingrobots moving your suggestion over to #147 :) this is last week's agenda, sorry about that!

**Comment by sparklingrobots** [comment]
@sugaroverflow Hahah, I literally have no idea what day it is.  Thanks for clearing that up.
