### ISSUE TITLE
Logo tweaks

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#17]
Based on the feedback in #12, tweak the logo a bit.  We'd need to think about using it:

- as an avatar for twitter/github/etc
- as a small sticker
- as part of print material like a flyer/letterhead
- probably places I'm not thinking of.

**Comment by star-szr** [comment]
I've updated the logo and made a bunch of mockups of it being used in various places. Feedback please!

I'd like to do at least one or two more mockups (for example Twitter icon in a phone app, since it's much smaller there), but this is what I had time to put together today :)

I'm attaching the SVG too, but the canvas size is a bit off. The final file will have an appropriately sized canvas/viewbox.

[Logo - SVG.svg.txt](https://github.com/drupaldiversity/administration/files/721628/Logo.-.SVG.svg.txt)

300px:
![logo - white 1x](https://cloud.githubusercontent.com/assets/327943/22179311/babb3280-e01d-11e6-92bc-b51d73e77237.png)

600px:
![logo - white 2x](https://cloud.githubusercontent.com/assets/327943/22179301/7c23927e-e01d-11e6-8338-053bd273b8c3.png)

Diecut sticker mockup:
![sticker](https://cloud.githubusercontent.com/assets/327943/22179302/7c2efd4e-e01d-11e6-983b-615e54082c12.png)

Website mockup:
![website](https://cloud.githubusercontent.com/assets/327943/22179304/7c380704-e01d-11e6-8e05-1770a44f9515.png)

Twitter mockup:
![twitter](https://cloud.githubusercontent.com/assets/327943/22179303/7c30593c-e01d-11e6-9d33-2ef33e916a70.png)

GitHub mockup:
![github](https://cloud.githubusercontent.com/assets/327943/22179298/7c18ba84-e01d-11e6-96f7-b390b2e34d5e.png)

**Comment by drnikko** [comment]
This looks great.  Thank you so much for all your hard work on this @Cottser!!!  <3 <3 One question though: I wonder how it would be to include the druplicon's eyes - only because this logo reminds me of logos for a few fertility clinics.  I realize this is just my weird interpretation & I'm not a designer.  Just wondering if there's a way we can more closely tie it to drupal on first glance.

**Comment by rubyji** [comment]
I agree, Nikki. And/or give the drop more of the trademark shape with the point going to the side a bit.

**Comment by star-szr** [comment]
I think what I've presented so far is in line with the current Drupal ecosystem and branding. For example, the Drupal.org homepage now has a symmetrical drop enclosed in a circle icon on the top left. I know we're unofficial, but Druplicon is kind of fading away the way I see it.

Druplicon is generally not seen as welcoming. There have been loooong issue threads discussing that as well as various blog posts. I'd like to avoid evoking Druplicon if we can, and I'd like what we come up with to be able to last us at least a few years without looking dated.

- https://www.drupal.org/node/2057767
- https://baheyeldin.com/technology/drupal/druplicon-has-freaky-eyes.html

@drnikki I'd be curious to know more about the fertility clinic connection because that's not what we are going for here :) is the resemblance stronger here than in the initial concept? Visuals would be great but if you can describe it in words that would be helpful too.

I also want to point out a kind of visual pun that is part of this logo, before we get into too much further tweaking. Another interpretation of this symbol is an abstract version of an opened mouth, where the drop coming down is the uvula (the dangly bit at the back of your throat). I made this connection when developing the concept and I think it works for what we are trying to do with this group. At least part of what we are doing is working to amplify different voices and make some noise. Maybe this connection is too obscure/too much of a stretch, but on the other hand, maybe it resonates with folks and is worth preserving.

I have some other thoughts, but I'll cut this short for now. Thanks for the feedback @drnikki @rubyji!

**Comment by sugaroverflow** [comment]
I think it looks great! It reminds me of the [Drupal 8 logo](https://www.drupal.org/files/drupal%208%20logo%20isolated%20CMYK%2072.png) in color and style. And it feels really clean and neat on those mockups. (I really want the sticker!)

Also, I'm attaching a screenshot of the Drupal.org homepage drop logo here for reference. I think seeing it really highlight's @Cottser's point about branding consistency:

<img width="171" alt="screen shot 2017-01-23 at 10 25 06 pm" src="https://cloud.githubusercontent.com/assets/6685950/22232978/cdbd12d8-e1ba-11e6-9497-71af7c2b35c1.png">

**Comment by cleverington** [comment]
I would actually agree with @drnikki. To me there's another visual there which we weren't fully intending, I think.

I believe just separating the drop from the heart (like shifting it just a few pixels towards the middle) would be enough to change the look.

Seeing the sticker upside down might help to see what I am seeing:

![sticker_dd i](https://cloud.githubusercontent.com/assets/1015474/22299083/730dda5a-e2e8-11e6-957e-b060f25672d2.png)

**Comment by star-szr** [comment]
Sorry that this took so long to come back to. Please leave your feedback about this revised version. At the end of the comment I've included an upside down sticker to compare with @cleverington's.

[Logo - SVG.svg.txt](https://github.com/drupaldiversity/administration/files/768214/Logo.-.SVG.svg.txt)

300px:
![logo - white 1x](https://cloud.githubusercontent.com/assets/327943/22851082/9a8f56bc-efe5-11e6-8861-316f27ed7850.png)

600px:
![logo - white 2x](https://cloud.githubusercontent.com/assets/327943/22851080/9a89738c-efe5-11e6-9ad1-67e919740497.png)

Sticker:
![sticker](https://cloud.githubusercontent.com/assets/327943/22851081/9a898890-efe5-11e6-9bfe-38cd4b2dd25f.png)

Website:
![website](https://cloud.githubusercontent.com/assets/327943/22851077/9a870606-efe5-11e6-978f-b03493e93fdc.png)

Twitter:
![twitter](https://cloud.githubusercontent.com/assets/327943/22851078/9a882a22-efe5-11e6-9fbc-988a35c3e86f.png)

GitHub:
![github](https://cloud.githubusercontent.com/assets/327943/22851079/9a892f62-efe5-11e6-8421-0a59b070cbcd.png)

----

Flipped sticker:

![sticker-flipped](https://cloud.githubusercontent.com/assets/327943/22851099/0626a8ee-efe6-11e6-9ee7-e23838d73152.png)

**Comment by cleverington** [comment]
@Cottser Looks amazing!  Got my vote 110%!

**Comment by HellooooNewman** [comment]
Looks great @Cottser

**Comment by rootwork** [comment]
Love this! Great work. And restoring my faith in design-based issue queues :)

**Comment by drnikko** [comment]
Closing this with great gratitude to @Cottser for getting this done.
