### ISSUE TITLE
Explicit Community Values

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#22]
In the wake of current (American) political events, I think it's particularly important that we are explicit about the things that we stand for.   

I feel that it's also important that this is crowd-sourced and not simply the work of one or two voices.  

We can work out the smoothness of it over time, but I'd to start with  **things it should include that are important to you**. 

Here are some examples of things that are important to me (not an exhaustive list):
- we are anti-racist
- we acknowledge that there are a spectrum of gender identities
- we believe that having people from different backgrounds makes everyone's experiences better

**Editing March 25** These values represent the DD&I Working Group and should prioritize diversity, inclusion, safety, respect.

**Comment by cleverington** [comment]
## DD&I Position Recommendation

- We support all measures which support inclusion, building a diverse Community, and supporting everyone
- We acknowledge gender identity is defined by who a person *is*, as opposed to who everyone thinks they should be
- We do not support measures which separate us from our neighbors, whether by town, by country, by union, or by business
- We believe in the power of many different peoples making experiences better for all people

**Comment by eaton** [comment]
> We support all measures which support inclusion, building a diverse Community, and supporting everyone

Perhaps this could be rephrased as: "We support all measures that build a diverse, inclusive, supportive community; and welcome any who share those principles."

One of the challenges many online communities have experienced is articulating the difference between "inclusiveness" and "welcoming people who oppose inclusiveness." Articulating that this is a shared set of ideals, and that all others who share them are welcome, helps answer the "Diversity must include people who don't want diversity, or it's not really diverse" objection that comes up so frequently.

**Comment by rpsu** [comment]
Things that are important for me are
* we do not need to accept anyone, but recognise the value of everyone 
* we take actions to make Drupal Community inclusive and welcoming to everyone (who shares our principles of openness and value of diversity etc.) 
 * we consider Drupal Community to be global and do not tolerate any kind of abuse or discrimination (religion, race, county of origin, sex, sexual orientation, nationality etc)

**Comment by bradleyfields** [comment]
The Pixar fan in me thinks _anyone can contribute_ is a useful adaptation of _[anyone can cook](http://pixar.wikia.com/wiki/Anyone_Can_Cook)_ for us.

Also, +1 to eaton's point re: people readily trying to warp what inclusion means. Maybe articulating some version of _not every opinion is an ideal_ could support the "shared set of ideals" thought. Not every mere expression is welcome.

A suggestion I don't mean for us to take literally, but does capture my feelings: _it's a community, not a free-for-all_. We're moving towards something, not just existing.

**Comment by drnikko** [comment]
I love the idea of "We're moving towards something, not just existing."  This can help draw some boundaries around the beliefs we hold because they _help us move toward something._  Of course everyone has the right to believe anything when they're just existing in the world. In order to contribute, we need people to be on board with our position. (words are hard today...)

**Comment by sparklingrobots** [comment]
I know this one is a priority pre-DrupalCon, but every time I come to give feedback, I get stuck on the same question: What is the form a position statement would ultimately take? 

I'm familiar with the mission/vision/values statements from the non-profit world, but forgive my ignorance--I have no idea what a position statement should look like. When I googled I found a bunch of pretty long documents from places like hospitals detailing specific policy positions, which didn't seem right. 

Are we looking for a short list of bullet points a la @cleverington's original response? A manifesto? A mission statement? 

I like writing and would be happy to draft up something based on what's here--but I would love some input on what form this position statement would ideally take (maybe some examples?).  

Or maybe I'm jumping ahead and it's still brainstorming time. Either way I figured I'd share what I've been struggling with on this in case it is helpful.

**Comment by mikemiles86** [comment]
@sparklingrobots I agree, having a full position statement is important, as is having a brief summed up mission statement. A powerful phrase that signifies the drive and purpose of the group.( I <s>could</s> am  also be biased about this, since I work for a digital marketing agency.)

I think creating a one sentence mission statement could be a powerful piece for the group at Drupalcon.  

The group already has the start of one on the [About us](https://drupaldiversity.github.io/about/) page "To continue the conversation about diversity and inclusion within Drupal". Are we happy with that, do we feel it captures the group?

I did some research and here are a few examples of Mission Statements I found:

"Exploring the forms and futures of human difference and diversity." - Diversity in Organizations, Communities & Nations Research Networks

"An inclusive community, a better nation." - National diversity Council

"Inspiring all girls to be strong, smart, and bold" - Girls Inc

**Comment by catch56** [comment]
"we consider Drupal Community to be global and do not tolerate any kind of abuse or discrimination (religion, race, county of origin, sex, sexual orientation, nationality etc)"
This sentence as worded (the wording, not the intention) concerns me, because twitter's current account locking strategy is based on a very literal/limited meaning of 'abuse' as in 'swearing at someone'. 

This means that fascists denying the holocaust, posting pictures of concentration camps,  threatening to gas or deport people do not get their accounts locked, but people swearing that those fascists do (and this isn't a Godwin, it's what's actually happening quite regularly).

http://www.theverge.com/2017/2/24/14719828/twitter-account-lock-ban-swearing-abuse-moderation was an early article when the policy went into action.

As soon as things move from values to actions, it starts to get a lot more muddy. Obviously there needs to be policy around actions too, but it's easy to get led into false equivalences (or balance in the wrong direction) as twitter clearly has. This isn't just an algorithmic issue on twitter's part since some of the fascists being sworn are also twitter verified accounts.

**Comment by japerry** [comment]
I think the issue with the diversity and inclusion part is that.. eh, as much as I don't like it -- diversity and inclusion means also allowing those with beliefs like 'trump could be a good president'... I've seen many people talk about the KKK being compared to Gorean philosophy.. but there is a difference, KKK discusses actions of violence, and that is not something he, nor other conservative Christians believe. Those are pretty extreme, but what about more mainline disagreements, like Drupalists...
 ... donating money to support Prop 8 (anti-gay measure in California)
 ... protesting at a planned parenthood
 ... Believing their wife should stay at home and take care of the children instead of working outside the home.
 ... Voting and supporting those who don't believe transgendered people should use the bathroom they feel comfortable with.

These are all mainstream conservative/religious views, all of which I disagree with, but would never remove them from our community for them. I worry that making a value system would be a brand of 'diversity and inclusion' which would be anything but.

**Comment by catch56** [comment]
"Voting and supporting those who don't believe transgendered people should use the bathroom they feel comfortable with."

Anything to do with conventional representative electoral politics is tricky, because parties/candidates have manifestos covering multiple issues at the same time.  You might support the entire platform, you might support some things and not care about the others, it might be a protest vote against the other options where you don't like any of them. So you can't tell someone's actual political views from a vote or candidate support, you can get a general idea, but not on every specific issue.

Similarly with religion, religious views are very complicated and the extent to which people apply them personally vs. at a societal level, or the extent to which they conflict with other parts of their life and belief systems are complex. If they say something about the specific issue, then you'll know though.

So if someone's vocally campaigning _specifically_ against trans people being able to use the bathroom of their choice (for example repeatedly posting about it on twitter, posting on a DrupalCon comment thread about it), then their presence at a conference (especially as a speaker or track chair) could directly discourage trans people from attending the conference, submitting sessions etc.

In that latter more explicit case, you're balancing a marginalised identity with a vocally held opinion against that identity, and these aren't equivalent things that need to be equally balanced.

So if you choose to be inclusive _in theory_ to everyone except people with swastikas tattooed on their necks, then _in practice_ you're excluding a lot of people by default.

**Comment by donquixote** [comment]
Who is "we" and what happens to those who don't?

I find that any statement of "we believe" has a gross smell to it.
I see no problem in trying to achieve a general atmosphere and conditions on events and in discussions (e.g. issue queue) where people of various groups feel safe / accepted / encouraged / empowered.

Putting the wrong people, or too many of them, into positions in charge or on a stage can thwart this goal. But this does not mean that everyone who is ever in charge or on a stage somewhere must subscribe to the whole package all the time.

Values in society evolve over time, and so do beliefs of an individual. Most often at different speeds for different individuals, and for different parts of society.

Instead of defining what someone believes, define what goals you want to achieve in terms of how people should be treated in the community.

**Comment by donquixote** [comment]
There is an important distinction to be made between communities where someone can add and remove people for various criteria (A), communities where people largely enter and leave by their own choice (B), and communities where some outside criterion has put people into a box, and now they have to get along (C).

An example for the first would be your group of friends, or a relationship. You can unfriend people who you do not want to associate with.

An example for the second would be a restaurant or museum or swimming pool. You can enforce some house rules, but you do not remove people for their beliefs. You observe the nazis and kick them out when they harrassing a kid, but not before. You also would never, ever, say that you and all visitors of this swimming pool believe xyz.
The reason why people join your club (enter the bar, etc) may be because they share your beliefs. But it could also be because they just want a drink. Nothing is wrong with the latter, it just has to be clear that only because you allow someone in your bar does not mean you subscribe to their belief system.
This has limits: If you notice that your bar is turning into a mafia joint, you probably want to intervene. If it is not too late already.

An example for the third type would be an island, where you are just stuck with whoever happens to live there. Some inhabitants might not even like the place.
Here you need to find rules that allows people to get along. But you are not going to establish a belief system.
Another example would be a school class. The teacher can reprimand pupils who mob the kid with glasses. But removing the bully from the group is usually not an option. Also there is no way to control what the students believe (or I would not approve of a school which attempts to do so).

The Drupal community is somewhere in between.
The idea of "we believe xyz" only works for the type A community, or maybe type B if people join exclusively because they share the belief system, not because they want a drink.

**Comment by sugaroverflow** [comment]
Closing this with our PR #118 for our Statement of Beliefs.
