### ISSUE TITLE
Communities + Belief systems

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#30]
After a robust discussion in the #diversity-inclusion channel, we realize that it's better not to work in a bubble. There are likely organizations that are inclusive but also not permissive of things that are against core values. 

@logickal - can you find an example of a credo/statement that is both kink-friendly and also clear about what is acceptable?

**Comment by star-szr** [comment]
Posting this on behalf of someone in the channel. They suggested we look to science fiction and comic conventions and at how they have dealt with serial offenders. "It's hard to make a requirement of x filed reports. The last straw just happens and then it needs to be dealt with."

Also relevant to #11 but I thought it fit in with what we're trying to do here.

**Comment by logickal** [comment]
@drnikki @Cottser The SF fandom community SEEMS like it would be a good place to look, but those codes of conduct are largely based around events/circumstances surrounding actual gatherings - the difficulty being that our community is not just DrupalCon, so the codes of conduct may not necessarily be applicable.

If you'd like an example, here is the policy for one of the largest and longest-running regional sf/comic/media cons: http://www.dragoncon.org/?q=convention_policies

SF Fandom (in general) is fairly socially liberal - but there are definitely lines drawn in terms of harassment and obvious bad behavior, which (again) are handled by going to convention staff, reporting the problem and handled on a case-by-case basis.

In terms of @drnikki's specific ask of me - I honestly question the need to specify something that is 'kink-friendly', because IMO it should be understood that this isn't a 'kink' issue - but unfortunately has been framed that way.

**Comment by jdegoes** [comment]
> There are likely organizations that are inclusive but also not permissive of things that are against core values.

This is a contradiction. What someone legally does in their bedroom with consenting adults should have no impact on their ability to participate in a professional community.

The idea of a professional community having "sexual values" is freakishly weird. An organization's values should lead to the creation of strategies, which should then lead to the creation of goals, and finally, to the utilization of tactics to obtain those goals.

No requirements on member's beliefs or values should be imposed, because if you want true diversity and inclusion, then the community must contain many people who believe and value different things (e.g. Muslim fundamentalist versus atheist transhumanist). These are irrelevant to the professional community. What matters is how people conduct themselves with other members of the community: do they treat each other professionally, with empathy, kindness, understanding, and eschewing all shaming, judging, and other abusive behavior? Or do they treat each other unprofessionally, insulting each other, judging each other, harassing and discriminating against each other?

Communities flourish or wither and die by how their members treat each other, not by esoteric values and beliefs stuffed into their heads which may or may not have any impact on whether they can conduct themselves as true professionals in their field of work, keeping their personal lives well out of professional spaces (and with it, their biases, kinks, and whatnot).

**Comment by adrienne** [comment]
I'm late to the party, but: I've been a member of SFF congoing fandom for 30+ years now and there is definitely a massively growing awareness of the need for codes of conduct and robust policies & procedures. (Also there have been a lot of fairly high-profile screwups regarding dealing with harassers, and a lot of public analysis & discussion of those incidents that might be useful to you.) Fandom is definitely VERY kink-friendly and I have literally never heard of a person getting thrown out of a con for consensual kink. 

I'll pull together some of those discussions and codes of conduct for you and put them here as i have time over the next few days, if you're still interested?

**Comment by drnikko** [comment]
@adrienne that would be great.  We're still working on ways to make our own values explicit (and inclusive) and outside examples would be really helpful.  thanks!

**Comment by sugaroverflow** [comment]
Closing this issue because we've explicitly defined our values as a group in our statement of values in #118  - thank you everyone for your help on this!
