### ISSUE TITLE
Explicit DD&I sharing policy

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#33]
We are making ALL THE THINGS EXPLICIT.  (see also #31)

@mlhess pointed out this sharing policy that the security team uses -https://www.drupal.org/node/2544896. 

We need a policy explaining what's okay to share and what's not okay to share from the DD&I channel on slack.

**Comment by Badfaerie** [comment]
PII should be left out of content when transferred out of the slack channel. Here's a great definition of PII:

> Personally identifiable information (PII) is any data that could potentially identify a specific individual. Any information that can be used to distinguish one person from another and can be used for de-anonymizing anonymous data can be considered PII.

**Comment by catch56** [comment]
The main Drupal irc channels weren't (and some still aren't) logged for a long time. However there's lots of quotes from them on issues, usually due people asking  "can I quote you on the issue".

Things in the DD&I channel are likely to be more sensitive in most cases, but sometimes it's useful to be able to attribute specific things if people are OK with it.

It's also worth noting that when you join a slack channel you get access to the backscroll (I think). While that's truncated due to volume, if something is anonymised and posted publicly within a week, there's a good chance someone could join the channel then find it retrospectively, although that's not much different to them already being in it.

**Comment by lyndsey** [comment]
Approach to text:
We want all voices
Don't take screenshots
If you do take screenshots ask and/or remove identifying information
The forum is essentially public, we can ask to not take screenshots but people can and may anyway.

Suggested text: 

The Slack Drupal Diversity & Inclusion channel is designed to be a place where we have discussions that move the issues of D&I forward. We do this because we believe in creating an inclusive and diverse community, and that in doing so we create a stronger, more sustainable project.

We don't all have to agree, but we do want the rights of people to speak up respected. We know that the loudest voices often find many and varied ways to be heard, but we also believe that all voices need to be heard in order to move forward. 

This forum should be considered public, assume that anyone can and may read anything posted here. We'd prefer people didn't take screenshots and post them in other forums, after all, this is where the discussion is taking place. Removing snippets of a conversation takes away context and can distort and stymie discussion. If you must take screenshots and post them to social media and other forums, it should be done with the permission of the person that posted it, identifying information should be removed.

**Comment by drnikko** [comment]
Added @lyndsey's text to : https://docs.google.com/document/d/1jSQ_UJhV9ZQUxVkdDfsBlQ8YfuO5EtV82HWwiunZ_T8/edit# which contains our moderation guidelines.  It feels like this is the best place for this.  If you want to add more, feel free to reopen and clarify.
