### ISSUE TITLE
#diversity-inclusion channel moderation team

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#34]
Note, this summary has been edited by people other than the original poster.
-------
Closing this issue,

continue iteration on guidelines in https://github.com/drupaldiversity/administration/issues/68
continue to sign up to moderate in https://github.com/drupaldiversity/administration/issues/69
get involved with administration and organization of teams (including moderation) in https://github.com/drupaldiversity/administration/issues/31
------- previous summary ----

Potential list of moderators (please add yourself here or make a comment below if volunteering):
@rubyji @AlannaBurke @YesCT @sugaroverflow @drnikki

This is a draft.
We worked on it from a google doc and sometimes copied content to this summary.
We used markdown in the google doc for easy posting in the repo later.

### Overview
DD&I spaces (these include online spaces like the slack channel, github repo, and physical spaces like DD&I-organized BoFs at events or DD&I tables in event exhibit halls) are dedicated to providing a harassment-free experience for everyone, regardless of gender and gender identity, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof). We do not tolerate harassment of Participants in any form. Sexual language and imagery is not appropriate.
### Participant Guidelines

Written specifically for DD&I slack, but to be adapted for other spaces.

1. Listen actively, read carefully, and be understanding.
  If joining a conversation, read the backlog. Give other Participants the opportunity to communicate effectively.
  It can be helpful to assume good intent behind other Participants' statements. The channel includes a very diverse population, with Participants from all over the globe. Cultural and lingual quirks do exist.
2. Speak from your own experience, instead of generalizing, and recognize the worth of others' experience.
  Use "I" instead of "they," "we," and "you".
  All Participants should recognize that all other Participants have their own experiences.
  Instead of invalidating another Participant's story with your own spin on their experience, share your own story and experience.
3. Challenge ideas, feelings, concerns, or one another by asking questions, but refrain from personal attacks -- focus on ideas first.
  Verbal challenges, backhanded insults, gender/race/region stereotyping, etc. are often exclusionary and should be avoided.
4. Participate to the fullest of your ability and availability.
  Community growth depends on the inclusion of individual voices. The channel wants you to speak up and speak out.  Everyone has a different amount of time to contribute. We value participation here if you can give 5 minutes or 5 hours. 
5. It is not a goal of inclusion to agree.
  The goal is to gain a deeper understanding of each other and **act** on that understanding with empathy to create a more welcoming, inclusive, and *safe* environment.
6. Be conscious of language differences and unintended connotations.
  "Text is hard".
  A statement said in jest about "apples" can carry connotations above and beyond any intended verbiage, even when talking about "what is a good snack?" Ask questions to clarify meanings and intentions.
7. Acknowledge individuals' identities.
  Use stated names and pronouns, do not challenge a person’s race, sexuality, disability, etc.
  If you are unsure how to address someone, for example what pronouns to use, just ask them discreetly and respectfully.
8. Some off topic conversation is OK.
  Some cross posting of announcements and off topic conversations is OK. But, do not do thread hijacking, spamming, commercial advertising, overt self-promotion, excessive going off-topic and incorrect content placement or timing. Consider announcing more appropriate places or times for in-depth off-topic conversations.
9. Share content from inside DD&I spaces with other spaces judiciously and without harassment.
  - The scrollback of slack is limited. Get permission from Participants to summarize or quote them in more permanent places, for example: posting meeting notes in the DD&I github repo, opening a DD&I github issue, adding a comment to a DD&I github issue, etc.
  - Admins of the Drupal slack team do have access to an archive of the entire slack history of public channels and private message.
  - When sharing content in public, for example: on twitter, in a blog post, in an article, on a podcast, etc, permission from Participants *must* be obtained first.
This forum should be considered public, assume that anyone can and may read anything posted here. We'd prefer people didn't take screenshots and post them in other forums, after all, this is where the discussion and work in progress is taking place. Removing snippets of a conversation takes away context and can distort and stymie discussion. If you take screenshots and post them to social media and other forums, get permission of the person that posted it. When getting permission include the option of removing identifying information. Permission is still needed even if identifying information is removed.
10. Address complaints between one another in the space when safe and appropriate.
  - When safe, try to clarify and engage in the space where the conflict happened, for example in the public DD&I channel.
  - Ping moderators when conflict is escalating (mention @di-moderators in slack).
  - Ask for help.
  - Suggest taking a break. When possible, suggest a time for reengaging.
  - When the topic of conflict is off topic for DD&I consider moving the conversation to a public channel more appropriate for that topic, for example: #governance
  - Contact the Drupal Community Working Group. https://www.drupal.org/governance/community-working-group 

### Additional considerations for in-person DD&I spaces

1. Follow the event's Code of Conduct, if there is one.
2. Do not touch people, their mobility devices, or other assistive equipment without their consent. If someone asks you to stop a certain behavior, cease immediately.
## Policy

DD&I has no tolerance for any activity which could be construed as:
- incitement to racial hatred
- incitement to religious hatred
- or any other behaviour meant to deliberately bring upon a person harassment.

We do not tolerate harassment on the grounds of gender and gender identity, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof). We do not tolerate harassment of Participants in any form. 

We run with a zero-tolerance policy for libel and defamation. 

While we believe in the concept of freedom of thought and freedom of expression, we do not operate on the basis of absolute freedom of speech and we impose limitations, for example, on "hate speech".

We reserve the right to terminate anyone's access to the DD&I spaces.
## Moderation Guidelines
Written specifically for slack, but to be adapted for other spaces.
### Moderation Responses

**Generally**
In DD&I spaces, strive to promote understanding, empathy, and increase personal awareness of all people from across the Drupal Community and the greater Technical Community, even those one may personally disagree with.

**Intentionally disruptive individuals get kicked, not tiered.**
The person kicked can PM the kicker or another Moderator, if desired, for re-admittance. If a disruptive person is engaging in what appears to be intentionally inflammatory, bullying, or harassing behavior provoking hostile responses (or acting in a hostile manner), kicking is faster and easier than trying to placate a disruptive person whose behavior is causing distress to other channel members.

The kick is *not* a ban. There are times when disruptive or "triggering" comments and statements are genuine and break the lines of communication between two parties. By speaking with a Moderator, the (potentially) disruptive person can be coached on using more sensitive, inclusive, and diverse aware verbiage, and on engaging in a more constructive manner.

1. Tier One Response
  User is welcomed in the channel, asked to read some scroll back, and given a link to participation guidelines.
2. Tier Two Response
  User is gently reminded in channel to keep posts on topic, and/or of participation guidelines.
3. Tier Three Response
  User is PM'd by available Moderator to clarify how their posts are out of line and given suggestions of what to do differently.
4. Tier Four Response
  If behavior continues, User is kicked for no less than 24 hours.

- Non-Tiered Response Banning
  (Example: User makes threats, statements intending to cause personal harm, etc. )
  User is reported, with screenshots or transcript from the archive, to the Drupal Community Working Group, and banned from the Channel until Moderators and the banned person can meet to discuss channel behavior.
### Moderation examples
- We're veering off-topic, and we need to get the _channel_ back on track.
- We are, again, on the border of #governance so would like to remind you that unless we have a _specific_ idea about procedures that will impact diversity and inclusion, to please hop over to that room.
- Thank you for being willing to move governance topics to that channel. There IS overlap, they do intersect, and people's feelings about one impact the other.  There are no perfect boundaries, but - like with everything else - we're trying to set a few.
- ...more examples
### Tips for slack moderators
- Add di-moderators to slack preferences as a highlighted word.
- When changing your role from a participant to a moderator, indicate this by prefacing your moderator statements with an indicator, for example: Putting my moderator hat on… Acting as a moderator now… When switching back, add clarity to your role using phrases for example: Taking off my moderator hat… Stepping down from moderating now… In my opinion… Speaking as myself…
- Keep self care in mind. Announce when you are not in a place to be a moderator. Announce when you are taking a step back or taking a break. When possible, give an estimate for when you will next be available.
- Create and use slackbot responses when appropriate. https://drupal.slack.com/customize/slackbot Consider making them short and convenient to type while unique enough they will not be automatically triggered when not intended, for example: preface with ! like "!di stay on topic", "!di guidelines", etc.
## Resources
- http://blog.socious.com/online-community-management-an-overview-on-community-moderation-guidelines
- https://www.drupal.org/irc/courtesy
- http://www.edchange.org/multicultural/activities/groundrules.html 
- https://alterconf.com/code-of-conduct 

-------
original issue opening:
If this is something we want... we need volunteers willing to help guide (and keep safe) the conversations in the #diversity-inclusion channel (and, still, need to make explicit what those guidelines are.) 

So, if you'd like to help moderate - post here.  If you have suggestions on moderation guidelines (examples from other communities would be great) - also post here.

**Comment by drnikko** [comment]
from @hrodig "avoid labeling people"

**Comment by rubyji** [comment]
I have a lot of experience in community moderation and I'm willing to take a shift doing it, but I think figuring out our own guidelines for this is actually a huge task, especially given the amount of heat around this right now. I can't imagine we'd be able to get this in place before DC, given all the other stuff we also need to do.

I'm surprised someone hasn't started a separate Slack channel for discussion of this issue. Or maybe they have and didn't invite me. ;-)

**Comment by hrod** [comment]
I think it is entirely appropriate to incorporate in the guidelines for folks engaging in the DD&I channel to reflect upon the social and economic advantages that they've been privileged to enjoy in their lives and realize that their experiences may not apply to all participants in the community-- and that's a major part of why we're here! 

Also, this blog post (http://blog.socious.com/online-community-management-an-overview-on-community-moderation-guidelines) has some good suggestions:

> Start with a basic outline of appropriate community etiquette. A concise list of items to consider is:
- Unacceptable content and materials, such as those of an obscene, graphic or pornographic nature
- Inappropriate behaviors, such as hazing, bullying, defamation and intolerance
- Unacceptable community usage, such as commercial advertising or overt self-promotion
- Improper posting practices, such as thread hijacking, spamming, going off-topic and incorrect content placement
- How community members should handle complaints between one another

**Comment by AlannaBurke** [comment]
I'd like to help moderate - I think we'd absolutely need short defined shifts when things are hopping like they are now. I've barely logged in since Friday because I just burnt myself out, and there are so many new folks, and it seems like the conversation is really cyclical. I've seen a lot of complaints about technical limitations, but there are certainly other ways to point people to information saying "these are the rules of posting here, this is what we know, this is what isn't acceptable behavior in this discussion, now you may post" - pretty common in most forums. Of course, we'd have to define all of that first.

**Comment by cleverington** [comment]
--- Updated 20171008 --- 20:30 CST

I fully approve of the Moderation stance and agree guidelines are a necessity.

However, I believe we need two sets: **Moderation Guidelines** and **Participation Guidelines**

Being reactionary and (though possibly accidentally) exclusive in the DD&I channel would be a bad thing from either Moderators **or** Participants.

The Drupal IRC Policy is probably a good starting point, which uses the Office Policy of Freenode, as quoted:

> In accordance with UK law, freenode and the PDPC have no tolerance for any activity which could be construed as:
> - incitement to racial hatred
> - incitement to religious hatred
> - or any other behaviour meant to deliberately bring upon a person harassment, alarm or distress. We do NOT tolerate discrimination on the grounds of race, religion, gender, sexual preference or other lifestyle choices and run with a zero-tolerance policy for libel and defamation.
> 
> While we believe in the concept of freedom of thought and freedom of expression, freenode does not operate on the basis of absolute freedom of speech and we impose limitations eg. on "hate speech".
> 
> We expect all members of the community to treat other community members with respect and reserve the right to terminate anyones access to our services should they be found to be in breach of policy.

Boils down, at a start, to "no hate-mongering". Not a bad thing, imho.

I am also amused that the link-title is simply named 'Courtesy': https://www.drupal.org/irc/courtesy 

However, I feel the IRC policy may be insufficient for the DD&I Channel simply because we **do** often deliberately discuss topics which cause distress. Instead, I feel we should expand the ideal to include *methods* of discussion, mutual respect, and then move on to levels of Moderation & tiered responses.

## Initial Draft / Thoughts

**Note** - These are just my initial knee-jerk thoughts and definitely not clear or concise enough to be Guidelines for either.

I almost wonder if we should have a CoC **just** for the Diversity & Inclusion Channel.....

### Participant Guidelines

Initial from http://www.edchange.org/multicultural/activities/groundrules.html and then edited heavily from there.

**1. Listen actively, Read Carefully, and Be Understanding**
Respect others when they are talking. If joining a conversation, read the backlog. Give other Participants the opportunity to communicate effectively.
It is also important to read for the *intent* behind a fellow Participant's statement. The channel includes a very diverse population, with participants from all over the globe. Cultural and lingual quirks do exist.

**2. Speak from your own experience instead of generalizing and recognize the worth of others' experience**
Use "I" instead of "they," "we," and "you".
All Participants should recognize that all other Participants have experience which should be respected.
Instead of invalidating somebody else's story with your own spin on her or his experience, share your own story and experience.

**3. Do not be afraid to respectfully challenge ideas, feelings, concerns, or even one another by asking questions, but refrain from personal attacks -- focus on ideas first.**
Verbal challenges, backhanded insults, gender/race/region stereotyping, etc. are often exclusionary and should be avoided.

**4. Participate to the fullest of your ability**
community growth depends on the inclusion of every individual voice. Do not be afraid to speak up and speak out.

**5. The goal of inclusion is not to agree**
The goal is to gain a deeper understanding of each other in a respectful manner and **act** on that understanding & empathy to create a more welcoming, inclusive, and *safe* environment.

**6. Be conscious of language and unintended connotations**
One of our Slack Participants said it best: "Text is hard".
A statement said in jest about "apples" can carry connotations above and beyond any intended verbiage, even when talking about "what is a good snack?"

### Tiered Moderation Response Example / Thoughts

**Golden Rule**
Strive to promote understanding, empathy, and increase personal awareness while remaining respectful of **all** people from across the Drupal Community and the greater Technical Community, even those one may personally disagree with.

**1. Intentionally disruptive individuals get kicked, not tiered.**
They can PM the kicker or another Moderator, if desired, for re-admittance, but I feel this one should probably be unilateral. If a disruptive person is engaging in what appears to be intentionally inflammatory, bullying, or harassing behavior to provoking hostile responses (or acting in a hostile manner), kicking is faster and easier than trying to placate you and possibly causing distress to other channel members.
> I cannot recall the User, but when starting up we had someone from Twitter follow a member into the Channel and proceed to harass an existing participant with personal attacks and intentionally misleading / leading questions intended to paint the participant in a bad light.
(Based on the Participant Guidelines)

**NOTE:** - The kick is *not* a ban. There are times when disruptive or "triggering" comments and statements are genuine and merely a break in lines of communication between two parties. By speaking with the Moderator, the (potentially) disruptive person can be coached on using more sensitive, professional, inclusive, and diverse aware verbiage.

> I'll reference my own prior experience in/on this. Was triggering a few Members of the group early-on when asking questions on a topic because I was truly confused/ignorant. A few short PMs helped me understand without causing further undue distress.

**2. Tier One Response**
User is gently reminded to keep thoughts and feelings professional and respectful.

**3. Tier Two Response**
User is PM'd by available Admin and reminded to keep thoughts and feelings professional and respectful.

**4. Tier Three Response**
If behavior continues, User is kicked for no less than 24 hours.

**5. Non-Tiered Response**
(Example: User makes threats, statements intending to cause personal harm, etc. )
User is reported, with screenshots, to the CWG and banned from the Channel until Moderators can meet to discuss actions/verbiage used.

## Final Thoughts

As I'm finishing up these thoughts, it occurs to me that we may also want to think about drafting Diverse-&-Inclusive Language Guidelines and/or adopt someone elses (like Drupal does with Freenode's Policies above).

**Comment by EclipseGc** [comment]
@cleverington I really like a lot of what you've got here. I think my main point of contention is in the Golden Rule section:

> Strive to promote understanding, empathy, and increase personal awareness while remaining respectful of all other Channel Participants

I'd like to see this changed to include member of our community who are NOT in channel. I don't need to JUST be respectful about the person with whom I am debating, but also with regard to anyone who may be a current example. i.e. You don't get to characterize some member of leadership as [insert adjectives/nouns here] just because you disagree with a decision. Likewise, you should not characterize someone in the process of being expelled as [insert adjectives/nouns here] either. It's unprofessional, unhelpful, and generally harms the community and its members.

**Comment by cleverington** [comment]
See https://github.com/drupaldiversity/administration/issues/11#issuecomment-289869425 for one area where this issue would come into play.

**Comment by EclipseGc** [comment]
Yes, characterizing someone as a troll, even if that's a legitimate interpretation of their behavior is unhelpful. I am FAAAAAR from the PC police, but I just don't see how name calling is going to make a difficult situation better.

**Comment by hrod** [comment]
@EclipseGc would reference back to saying that we should avoid labeling-- that said, it doesn't mean someone isn't engaging in trolling behavior; let's just not call them a name.

**Comment by hrod** [comment]
@cleverington Maybe rewrite to "person engaging in harassing and bullying behavior".

**Comment by cleverington** [comment]
Thank you @hrod and @EclipseGc for moderating my own out-of-line verbiage.

Though I think it might be more specific to say "disruptive person engaging in what appears to be intentionally inflammatory, bullying, or harassing behavior".

We don't want to be unilaterally kicking people, so generalizations may not be the best approach.

Post about to be edited.

**Comment by cleverington** [comment]
I'll also reference K.I.S.S. as an observation, should anyone want to help remove the Mark Twain'd influence.....

> “I didn't have time to write a short letter, so I wrote a long one instead.”

[― Mark Twain](http://www.goodreads.com/quotes/21422-i-didn-t-have-time-to-write-a-short-letter-so "Link to Quote by Mark Twain")

**Comment by YesCT** [comment]
I'll volunteer to be on the list of moderators.

**Comment by drnikko** [comment]
Here is a link to collaborate on moderation guidelines
https://docs.google.com/document/d/1jSQ_UJhV9ZQUxVkdDfsBlQ8YfuO5EtV82HWwiunZ_T8/edit?usp=sharing

**Comment by sugaroverflow** [comment]
+1 volunteer to moderate

**Comment by YesCT** [comment]
I edited in the google doc and posted in the "issue summary". Feedback welcome. Discussion in slack also welcome.

**Comment by lkopacz** [comment]
+1 volunteer to moderate

**Comment by YesCT** [comment]
https://github.com/drupaldiversity/administration/wiki/%23diversity-inclusion-moderation-guidelines-(v1)

**Comment by YesCT** [comment]
Moved moderator volunteering to https://github.com/drupaldiversity/administration/issues/69
Note https://github.com/drupaldiversity/administration/issues/31 is related, and about administration/organizing volunteering

Two are different roles. But same person could do both.
