### ISSUE TITLE
 Code of Conduct language examples from other communities

### ISSUE THREAD

**Issue by lauras** [drupaldiversity/administration#41]
This issue is really a place to drop example language from Codes of Conduct elsewhere to perhaps help inform our own process.

## Methodology:

1. Share the snippet and provide a link. (Try to keep each snippet specific to an aspect so we don't have thousands of words in each sample.)
2. (Optional) Offer discussion of why it's potentially helpful or illustrates a challenge or potential pitfall.
3. No language shared should be deemed as endorsement by the poster. We want to keep this a brainstorming process.

If this gets too cumbersome, we may split the issue into subtopics. But for now, I'm just trying to get various ideas raised into one place.

**Comment by lauras** [comment]
[From Wiscon](http://wiscon.net/policies/anti-harassment/code-of-conduct/) (a longstanding feminist SF conference that has struggled with diversity issues and CoC in recent years):

> Harassment
> 
> WisCon’s definition of harassment may not necessarily align with legal definitions of harassment. Harassment includes: Verbal comments or displayed images that harmfully reinforce structures of oppression (related to gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, geographic origin, or class); deliberate intimidation; stalking; body policing (including gender policing in all bathrooms); unwelcome photography or recording; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately. Exhibitors in the Dealer’s Room, volunteers, and Concom members are also subject to the anti-harassment policy.
> 
> Harassment does not include: respectful disagreement or critique in good faith. WisCon continues to welcome and appreciate the reading or performance of risky, transgressive material and the discussion of controversial ideas.

Sharing this for its specific language as to what constitutes harassment. Perhaps helpful?

**Comment by lauras** [comment]
Another from Wiscon:

> Incidents outside of WisCon
> 
> At times, concerns may be raised about members (or potential members) based on conduct that has occurred outside of WisCon that may include gross violations of our policy and/or put members at risk, including:
> 
> Individuals who have not attended WisCon, but have a history of abusive behavior and/or known incidents that took place outside WisCon that may cause risks to a member’s (or members’) safety, or which may contribute to a hostile or non-inclusive climate at the convention.
> WisCon members who have been reported to Safety for outside incidents, including (but not limited to) conduct at other conventions, threatening or abusive behavior online, or assault.
> These may be individuals who may or may not have expressed interest in attending the convention, and for whom reports may or may not have been filed, but who have come to the attention of the Concom’s Anti-Abuse Team.
> 
> WisCon considers online behavior to be just as important as offline behavior. Doxing or outing, online harassment or stalking, or deliberately connecting a pseudonym with a wallet name are all considered violations of our Code of Conduct and will be treated accordingly. These actions need not occur in WisCon-affiliated spaces (e.g., our blog) in order to be considered.
> 
> We understand that at times, our members will have disagreements or interpersonal conflicts that do not necessarily escalate to the point of harassment or abuse. WisCon will not arbitrate feuds; we ask that you please leave these conflicts at the door to the extent that you are able. If, however, conflicts escalate to the point that they 1) threaten member safety, or 2) violate our Code of Conduct or policies at the convention, the Anti-Abuse Team may become involved.

Sharing for its discussion of behavior outside of the community. This may or may not reach too far for Drupal, I don't know. But as behavior outside of the community seems to have been at issue recently, I thought I'd share this here.

**Comment by jdegoes** [comment]
Allowing a Code of Conduct to examine behavior outside the community will actively incentivize abuse from bad actors. If you do not like someone, for example, because they have a gender-expression that makes you feel uncomfortable, then all you have to do is devote some hours to rummaging around the Internet in the person's private communities and accounts, collect and take information out of context, and then engage in a smear campaign by exposing all this personal information to the outside world.

Not only does extending the reach of the COC support the abuses of bad actors (actively encouraging them to bring irrelevant details of a person's life to the professional community), but it also means the COC must be watered down, and therefore leave vulnerable people far less protected inside Drupal communities.

The reason for this is quite simple and obvious to anyone who has been part of a flame war on some random Internet forum (perhaps debating Star Trek versus Star Wars or some dumb thing). Most people have engaged in somewhat aggressive behavior in the heat of the moment — nothing like death threats, for example, but definitely language and tone that would ideally not be permitted in a COC. Yet if you extend the COC to cover behavior outside the community, then to avoid banning every single person who has ever participated in any heated discussion, it will be necessary to water the COC down to a point where it does not actually ensure professional, respectful, and empathic behavior to all those participating inside the professional community.

Another reason for not extending the COC to outside behavior is one of practicality. Every individual leaves a large footprint online, the sifting through of which would take days, weeks, or perhaps in some cases months. If we value equality and wish to treat people fairly, rather than showing favoritism on the basis of celebrity status or some such, then any report should undertake a comprehensive investigation of a person's online life — all possible information should be gathered into order to create a complete, comprehensive picture that is in context. Anything less than this level of rigor would be cherry-picking and would lead to unequal treatment, most likely based on status, which would be the exact opposite of welcoming, inclusive, and egalitarian. But as a practical matter, the amount of work involved in doing a thorough investigation of someone's expressed online behavior is prohibitive, so prohibitive that imposing that cost on every complaint could grind the system to a halt and tie up resources that would be better spent ensuring people are treated well inside Drupal communities.

A final reason for not extending the COC to outside behavior is that you have no control over the quality of or access to information in other communities. A malicious community could create a fictitious incident in which a Drupal member violates the Drupal COC (with numerous witnesses comprised of bad actors), and report this publicly, which would require Drupal look into the matter — without the knowledge, let's say, that this particular community was malicious — and result in expelling the member from Drupal for something that never happened, or perhaps, never happened in the way the malicious community described. If you want to be sure, it should be your members, your rules, your community, and your witnesses, which is yet another reason for focusing the COC on inside behavior.

For all these reasons, many existing COCs do not examine behavior in other communities.

For example, Contributor Covenant:

> This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community. Examples of representing a project or community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event.

And again in FCOP:

> These requirements on _behavior_ apply to _members_ only while they are actively participating in the _community_. The standing of _members_ is unaffected by _behavior_ that does not comply with these requirements if this _behavior_ occurs in other communities.

COCs were never conceived to encompass a person's whole life, but rather, to ensure common ground rules for group participation within professional communities. Rather than open up the COC to malicious and abusive behavior, water down behavioral requirements, increase workload on volunteers, and potentially make the COC open to exploits by malicious communities, the alternative of keeping the COC focused on in-community behavior seems all too obvious.

**Comment by damienmckenna** [comment]
Lets keep this discussion focused on identifying other reasonably good (for values of "reasonably good" as of yet undefined) Codes and highlight interesting portions of them, lets deal with the implications and implementation deals for other discussions.

**Comment by jdegoes** [comment]
@damienmckenna Good suggestion. Here are a few brief snippets from FCOP that may be useful:

> ## Statement of Purpose
>
> The Fantasyland Institute of Learning Code of Professionalism (FCOP) dictates the terms and conditions under which we allow you to participate in the _community_.
> 
> The purpose of FCOP is to facilitate an inclusive and diverse _community_ of professionals who productively work towards shared professional goals.
> 
> To facilitate these goals, we do not impose any ideology onto _members_, nor do we restrict participation based on people's _personal attributes_ or their _behavior_ in other communities. Instead, we restrict the _community_ to _civil_ individuals and we require that all _members_ refrain from _unprofessional behavior_.

The strong emphasis on diversity and inclusion and on keeping all behavior professional seem critical for any COC that wants to be welcoming and provide a safe professional space for members.

Another one:

> ## Welcome Statement
> 
> We welcome all _civil_ individuals regardless of any _personal attributes_ they have that are orthogonal to the professional goals of the _community_.
> 
> We pledge that we will enforce the terms and conditions set forth in FCOP, and that we will hold ourselves to these same standards, thereby setting a positive example for others to follow.

I think any COC should provide a clear welcome statement, so that people from underrepresented groups in technology will feel welcome. FCOP also includes things like body mods, gender-expression, presentation of appearance, sexual preferences, and all the standard categories, making it clear that the Drupal community will not discriminate on the basis of how people look or think. What matters is whether or not they can uphold the highest standards of professionalism, not whether they're into kink or are covered in tattoos or like to wear nose piercings. 

Keep things focused on professional behavior, leave your biases and judgments at the door.

Another snippet:

> We encourage everyone to assume the best in every interaction; to be open, honest, and empathic in all _communication_; and to demonstrate politeness and professional courtesy in every situation.
> 
> We welcome any closed group of _members_ to engage in any _behavior_ for which there is explicit and unanimous mutual consent. In the absence of such consent, we impose the following restrictions during _active participation_, which are further clarified by the **Glossary**.
> 
> * **Don't Harass**. Do not _interact_ with anyone who does not consent to the _interaction_.
> * **Don't Stereotype**. _Communicate_ as if every individual were unique.
> * **Don't Discriminate**. Do not show or withhold favoritism on the basis of a _stereotype_.
> * **Don't Shame**. Do not shame the _personal attributes_ of others.
> * **Don't Pry**. Do not attempt to infer the private content or _communication_ of others.
> 
> These requirements on _behavior_ apply to _members_ only while they are actively participating in the _community_. The standing of _members_ is unaffected by _behavior_ that does not comply with these requirements if this _behavior_ occurs in other communities.

I like the strong protections against harassment, stereotyping, discrimination, shaming, and prying. Without protections like these, you leave the door open to abusers who might harass, stereotype, discriminate, shame, and pry, creating a toxic, dysfunctional community that drives people away.

I also like the fact that if people don't want to play by these rules, they don't have to, so long as they have explicit, mutual consent for any other behavior.

Another snippet:

> ### Inactive Participation
> 
> During _inactive participation_, you must behave as required in this section, and as further clarified by the **Glossary**.
> 
> * **Don't Dox**. Do not disseminate _personal attributes_ you learn about _members_ in the course of _active participation_.
> * **Don't Retaliate**. Do not _retaliate_ against _aggrieved members_ for reporting an _incident_.
> 
> These requirements on _behavior_ apply to _members_ at all times, even when they are not actively participating in the _community_.

Let's face it: doxxing and retaliation are a problem in tech. I think the best policy here is no tolerance: you engage in either of these, and there need to be consequences.

There's lots of other good stuff, but there's one last snippet I really like:

>  * **Harassment**. We define _harassment_ as an _interaction_ with someone who does not consent to the _interaction_. For _interactions_ of a professional nature, you may assume consent for the first interaction, until the recipient _communicates_ otherwise (examples include handshakes, looking at someone who is speaking, providing feedback). For all other _interactions_, you must assume non-consent until the person clearly and unambiguously _communicates_ otherwise (examples include persistent gaze at someone who is not speaking, sexual interactions of any kind).

No interaction without consent. This is a very strong definition of harassment. Some would say too strong, but I disagree. If you do not want someone to interact with you — whether that's talking to you, staring at you, being in your personal space, gesturing to you, etc. — then you should have control over that interaction. This means if, for example, someone is making someone else feel uncomfortable in any way, that person has the right to say, "Please don't interact with me," and the first person has to comply. No one has the right to force you to engage with them.

All of these are really great ideas that I hope would find their way into the next COC. Or possibly, the Drupal community could simply consider adopting FCOP in its current form.

**Comment by catch56** [comment]
This is from a generic example CoC, not sure if it's specifically adopted anywhere, but I liked the explicit statement of priorities in this one. I wouldn't use this wording though since it assumes too much knowledge up front:
http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy

> COMMUNITY NAME prioritizes marginalized people’s safety over privileged people’s comfort. RESPONSE TEAM reserves the right not to act on complaints regarding:
> ‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’
> Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
> Communicating in a ‘tone’ you don’t find congenial
> Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions

Things that are good: recognises that the community does not exist in a vacuum where all other power/class relationships are discarded, and emphasises the actual meaning of statements over their superficial presentation.

If someone 'politely' starts promoting racial discrimination and someone else 'rudely' confronts them about it, a code of conduct that focuses the relative civility of that interaction and not its content is compounding that situation rather than helping to solve it. So I'm wary of anything that talks about civility as a neutral standard to aim for, civility or lack of it often isn't the problem and it can be very differently defined. The current Drupal code of conduct does mention 'poor manners' (although only as an aside).

**Comment by drnikko** [comment]
Just dropping in a link to our specific CoC recommendations issue: #39

**Comment by lauras** [comment]
My mistake. I didn't see that before so I started  this issue.

**Comment by lauras** [comment]
Suggest keeping this issue as a dumping ground for language elsewhere, and use #39 for discussion and recommendations.

In that spirit, here is [language from Mastadon.social's terms](https://mastodon.social/about/more). As you may note, they get QUITE specific. Excerpt:

> The following types of content will be removed from the public timeline, and may result in account suspension and revocation of access to the service:
> * Racism or advocation of racism
> * Sexism or advocation of sexism
> * Discrimination against gender and sexual minorities, or advocation thereof
> * Xenophobic and/or violent nationalism
>
> The following types of content are explicitly disallowed and will result in revocation of access to the service:
> * Sexual depictions of children
> * Content illegal in Germany and/or France, such as holocaust denial or Nazi symbolism
> * Conduct promoting the ideology of National Socialism
>
> Any conduct intended to stalk or harass other users, or to impede other users from utilizing the service, or to degrade the performance of the service, or to harass other users, or to incite other users to perform any of the aforementioned actions, is also disallowed, and subject to punishment up to and including revocation of access to the service. This includes, but is not limited to, the following behaviors:
> * Continuing to engage in conversation with a user that has specifically has requested for said engagement with that user to cease and desist may be considered harassment, regardless of platform-specific privacy tools employed.
> * Aggregating, posting, and/or disseminating a person's demographic, personal, or private data without express permission (informally called doxing or dropping dox) may be considered harassment.
> * Inciting users to engage another user in continued interaction or discussion after a user has requested for said engagement with that user to cease and desist (informally called brigading or dogpiling) may be considered harassment.

**Comment by jdegoes** [comment]
> If someone 'politely' starts promoting racial discrimination and someone else 'rudely' confronts them about it,

Neither racial discrimination nor rude behavior have any place *at all* in a professional community. That someone engages in one type of unprofessional behavior is not a license to engage in other types of unprofessional behavior. 

Incidents are judged on a case by case basis, and discretion will be used, so there is no need to explicitly allow or encourage unprofessional behavior—the expectation should be that _all behavior_ will be professional. 

There can be no, *"Well, if someone gives you a mean look, it's OK to punch them in the face."* Neither being mean nor punching people in the face is appropriate for a professional community, and if either happens, it must be dealt with in a sensitive and contextually appropriate manner.

**Comment by lauras** [comment]
Adding a banner that distills a CoC at a conference. Obviously conference context requires slightly different CoC than what would govern online behavior. Anyway, FWIW...
![coc](https://cloud.githubusercontent.com/assets/181019/25251058/4270b89c-25d5-11e7-9a49-6f82f6a72d62.jpg)

**Comment by sugaroverflow** [comment]
Closing this issue for now as we discussed it quite a bit and it informed some of our decisions in writing our Statement of Values.  We have some volunteers working on creating possible supplementary material to our CoC and these conversations would probably be helpful for them. 

Thank you for your thoughts!
