### ISSUE TITLE
Points of privilege

### ISSUE THREAD

**Issue by frankmuse** [drupaldiversity/administration#48]
Hi Everyone! I've been in the Drupal community for about 3 years now and I never knew about this group! It's obvious and unfortunate what brought me here, but I was so happy to find this little corner of inclusivity! This is a temp account for obvious reasons. I don't yet feel safe posting with my real Drupal Github account, but I hope someday I can (through the work of this group!).

First of all, THIS IS JUST AN IDEA so please don't attack me. Maybe we can implement a better version of this idea through DISCUSSION. This is kind of inspired the "Flags of Approachability" issue (which is a great idea!!)

So the idea is that commits or maybe even comments will each require a "point". Each user account will get a certain number of points per day. (I don't know what a good starting number might be... maybe 10). BUT users belonging to underprivileged or other disadvantaged groups each get 1 point for every group they belong to. So for example, a transgender hispanic individual would get two extra points per day.

Obviously some groups are more disadvantaged than others, but I don't think it will be productive to create some kind of comparative point system, so I'm just proposing one extra point per underprivileged group that a person belongs to. On Drupal accounts, we could have a list of everything you can check. Maybe users can even add "Underprivileged status" items themselves.

I know a lot of people are going to hate this idea, but I just want to say... think about what we could do with more DIVERSITY in our code and conversation!

**Comment by saltednut** [comment]
What are these points for?  Sorry, re-read now.

So I assume the cisgenered white male depicted in my profile photo gets 10 comments/commits a day.

That might not work out during code sprints but on an average day, okay.

I am not sure what this solves though. Lets look at some people that contribute a lot. I'll use a fake name, since that seems to be possibly offensive to cite an actual person. So we'll call this person Todd Plonkett as an example. Todd Plonkett is a cisgendered white male that makes upwards of 30-50 posts and commits per day. They are a core subsystem maintainer and essentially, contribute a lot to Drupal. Should that person be limited to 10 points?

If there is a critical security issue that requires a lot of commits and many many sites are vulnerable, do we make this individual wait 24 hours for their points to return?

Meanwhile, what of the underprivileged individuals that have 12 points per day and have not committed in months. Do these get backlogged? Do they go away? After 3 months will each of these people have 34 points never used while others are limiting their contributions?

Lets take a step back:  In the current system everyone, regardless of privilege, has unlimited points. They can comment, they can commit... why limit anyone, regardless?

**Comment by davereid** [comment]
The end result would be to limiting the amount of things people could do per day? I don't quite understand.

**Comment by saltednut** [comment]
Honestly I'm a little taken aback that you feel like you need to use a fake username and profile just to have these discussions. 

I do not think it is proper to respond to any issues further on grounds that it is neither fair nor inclusive that one should make a fake, possibly even trolling account to post these issues about inclusivity.

**Comment by catch56** [comment]
@frankmuse I'm not going to respond to the points system as such, it's not clear what the points would be used for (do I need to use points to commit other people's patches to core for example?).
However I think there's a conceptual issue with 'privilege' that's worth discussing.

When people talk about privilege, intersectionality and having multiple marginalised identities, it's not the case that simply adding up the number of identities gives you some kind of measurable level of privilege vs. not. This is often referred to as 'oppression olympics', and giving people points for each one looks like an almost literal interpretation of that concept.

Instead to give a very basic example, it just means that white men, white women, black women and black men tend to get treated differently in different situations. That the experience of 'women' and 'black people' or 'white people' or 'men' is not necessarily the same just because they belong to one group, because they simultaneously belong to other groups that get expressed in different situations. For a concrete example, white women in the US were given the vote before either black women or black men.

A couple of sources discussing the difference between intersectionality and 'oppression olympics':
http://geekfeminism.wikia.com/wiki/Oppression_Olympics
https://bottomface.com/2014/04/28/intersectionality-is-not-the-oppression-olympics/

http://www.huffingtonpost.com/gina-crosleycorcoran/explaining-white-privilege-to-a-broke-white-person_b_5269255.html also attempts to explain the concept of privilege itself without some of the assumptions that people often have.

**Comment by drnikko** [comment]
Closing this because we don't need to rank and quantify oppression.

**Comment by saltednut** [comment]
Thanks @drnikki
