### ISSUE TITLE
Collaborate on specific callouts for Drupalcon Nashville 

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#66]
"I’d like some reassurance that the google spreadsheet/doc/checklist for city/venue evaluation for drupalcon will NOW include check local laws for X."
^ We've been asked to support with a list of X

"I'd love to see DrupalCon address this _directly_ in keynotes and other attendee messaging."

**Comment by drnikko** [comment]
https://docs.google.com/document/d/1M1GcpRDXRDoXoJCQQCBSsoP_VjADzzIW5caAD8wcsec/edit

**Comment by heyrocker** [comment]
My first reaction is I'm not a huge fan of the fact that this stuff is lumped under "Misc" which completely minimizes its importance.

**Comment by justAChris** [comment]
Not sure how this fits in the document, but even with increased importance placed on D&I concerns during the RFP and selection process, we need to be prepared to evaluate and respond to the concerns of attendees up to the conference date. This is largely because local and state laws are always changing. The last two selections of note (New Orleans, Nashville) had/have impacting laws enacted in the year or two leading up to the actual event, possibly after the location was selected by the DA. The first 2 parts of the current Concerns/Callouts document (For those considering attendance, For attendees on-site) may end up being a continuing conversation for some future events.

Sources:
[http://www.cnn.com/2015/05/20/politics/bobby-jindal-religious-freedom-louisiana/](http://www.cnn.com/2015/05/20/politics/bobby-jindal-religious-freedom-louisiana/)
[https://www.theatlantic.com/politics/archive/2016/04/tennessee-haslam-counseling-law/480270/](https://www.theatlantic.com/politics/archive/2016/04/tennessee-haslam-counseling-law/480270/)

**Comment by sugaroverflow** [comment]
We shared these callouts with the DA and the rest is up to them now :)

Thanks for your feedback!
